# Copyright (c) 2021 aasaam software development group
image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  - docker login --username=$GITHUB_HUB_USER --password=$GITHUB_HUB_PASS docker.pkg.github.com

build:
  stage: build
  script:
    # build
    - docker rm -f geonames-postgis-build-app || true
    - docker rm -f geonames-postgis || true
    - docker rmi geonames-postgis || true
    - rm -rf var || true
    - apk add --no-cache wget ca-certificates p7zip bash util-linux
    - ./download.sh
    - docker pull postgis/postgis:13-3.1-alpine
    - docker pull golang:1.17-alpine
    - docker build --no-cache --tag geonames-postgis -f Dockerfile.db .
    - |
      docker run --name geonames-postgis --name geonames-postgis \
        -v $(pwd)/init.db:/docker-entrypoint-initdb.d \
        -v $(pwd)/var/geonames_extract:/geonames_extract \
        -p 5432:5432 \
        -e POSTGRES_PASSWORD=geonames -e POSTGRES_USER=geonames -e POSTGRES_DB=geonames \
        -d postgis/postgis:13-3.1-alpine
    - sleep 15
    - docker logs geonames-postgis
    - docker build --no-cache --tag geonames-postgis-build-app -f Dockerfile.build-app .
    - docker run --rm --entrypoint cat geonames-postgis-build-app /usr/bin/geodata > ./geodata
    - chmod +x ./geodata
    - ./geodata
    - docker stop geonames-postgis
    - docker cp geonames-postgis:/var/lib/postgresql/data var/data
    - docker build -f Dockerfile -t aasaam/geonames-postgis .
    # push
    - |
      docker push aasaam/geonames-postgis
      docker image tag aasaam/geonames-postgis docker.pkg.github.com/aasaam/geonames-postgis/geonames-postgis
      docker push docker.pkg.github.com/aasaam/geonames-postgis/geonames-postgis
    # remove image
    - docker rmi aasaam/geonames-postgis
    - docker rm -f geonames-postgis-build-app || true
    - docker rm -f geonames-postgis || true
    - docker rmi geonames-postgis || true
