# Copyright (c) 2021 aasaam software development group
image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  - docker login --username=$GITHUB_HUB_USER --password=$GITHUB_HUB_PASS docker.pkg.github.com

build:
  stage: build
  script:
    # build
    - docker rm -f geonames-postgis-build-app || true
    - docker rm -f geonames-postgis || true
    - rm -rf var || true
    - apk add --no-cache wget ca-certificates p7zip bash util-linux
    - whereis docker
    - pwd
    - ./download.sh
    - docker run --name geonames-postgis --net=host -e POSTGRES_PASSWORD=geonames -e POSTGRES_USER=geonames -e POSTGRES_DB=geonames -v $(pwd)/init.db:/docker-entrypoint-initdb.d -v $(pwd)/var/geonames_extract:/geonames_extract -v $(pwd)/var/postgresql:/var/lib/postgresql/data -d postgis/postgis:13-3.1
    - sleep 30
    - docker logs geonames-postgis
    - docker build -f Dockerfile.build-app -t geonames-postgis-build-app .
    - docker run --rm --entrypoint cat geonames-postgis-build-app /usr/bin/geodata > ./geodata
    - chmod +x ./geodata
    - ./geodata
    - rm .dockerignore
    - docker build -f Dockerfile -t aasaam/geonames-postgis .
    # push
    - |
      docker push aasaam/geonames-postgis
    # remove image
    - docker rmi aasaam/geonames-postgis
