version: "3"

services:
  postgis:
    image: aasaam/geonames-postgis
    container_name: geonames-postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=geonames
      - POSTGRES_USER=geonames
      - POSTGRES_DB=geonames
  adminer:
    image: adminer
    depends_on:
      - postgis
    container_name: adminer
    ports:
      - 8080:8080
