FROM golang:1.17-alpine AS builder

ADD . /src

RUN cd /src \
  && go mod tidy \
  && go mod download \
  && go build -ldflags="-s -w" -o geodata \
  && mv geodata /usr/bin/geodata

ENTRYPOINT ["/usr/bin/geodata"]
