name: ci

on:
  schedule:
    - cron:  '0 0 * * 0'
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: go version
      -
        name: Build
        run: |
          ./download.sh
          ./build.sh
      -
        name: Push image docker hub
        run: |
          docker push aasaam/geonames-postgis
      -
        name: Push image github container registry
        run: |
          docker image tag aasaam/geonames-postgis ghcr.io/aasaam/geonames-postgis
          docker push ghcr.io/aasaam/geonames-postgis
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: aasaam/geonames-postgis
